# Generated by Django 2.2.14 on 2020-07-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="files",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="addfile",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
